#Generated Form Function
function GenerateGlobalConfig {
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 05.05.2020 14:21
    # Generated By: severin.nauer
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $addButton = New-Object System.Windows.Forms.Button
    $label2 = New-Object System.Windows.Forms.Label
    $ruleGrid = New-Object System.Windows.Forms.DataGridView
    $label1 = New-Object System.Windows.Forms.Label
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    
    $fillGrid = { 
        Import-Module ".\Utils\config.psm1" -Verbose -Force
        $jsonConfig = (ImportConfig $configPath)
        $ruleGrid.Rows.Clear()
        foreach ($type in $jsonConfig.globalTypes) {
            $ruleGrid.Rows.Add($type.type, $type.rules.destination)
        }
    }

    $addButton_OnClick = 
    {
        GenerateRuleConfig -isGlobal $true -isNew $true
        . $fillGrid
    }
    
    $OnLoadForm_StateCorrection =
    { #Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 394
    $System_Drawing_Size.Width = 478
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Primal Form"
    
    
    $addButton.DataBindings.DefaultDataSourceUpdateMode = 0
    $addButton.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 363
    $System_Drawing_Point.Y = 355
    $addButton.Location = $System_Drawing_Point
    $addButton.Name = "addButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 93
    $addButton.Size = $System_Drawing_Size
    $addButton.TabIndex = 4
    $addButton.Text = "Add rule"
    $addButton.UseVisualStyleBackColor = $True
    $addButton.add_Click($addButton_OnClick)
    
    $form1.Controls.Add($addButton)
    
    $label2.DataBindings.DefaultDataSourceUpdateMode = 0
    $label2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 1, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 45
    $label2.Location = $System_Drawing_Point
    $label2.Name = "label2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label2.Size = $System_Drawing_Size
    $label2.TabIndex = 2
    $label2.Text = "File types"
    $label2.add_Click($handler_label2_Click)
    
    $form1.Controls.Add($label2)
    
    $ruleGrid.AllowUserToAddRows = $False
    $System_Windows_Forms_DataGridViewTextBoxColumn_1 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
    $System_Windows_Forms_DataGridViewTextBoxColumn_1.HeaderText = "File type"
    $System_Windows_Forms_DataGridViewTextBoxColumn_1.Name = ""
    $System_Windows_Forms_DataGridViewTextBoxColumn_1.Width = 100
    
    $ruleGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_1) | Out-Null
    $System_Windows_Forms_DataGridViewTextBoxColumn_2 = New-Object System.Windows.Forms.DataGridViewTextBoxColumn
    $System_Windows_Forms_DataGridViewTextBoxColumn_2.HeaderText = "Folder path"
    $System_Windows_Forms_DataGridViewTextBoxColumn_2.Name = ""
    $System_Windows_Forms_DataGridViewTextBoxColumn_2.Width = 300
    
    $ruleGrid.Columns.Add($System_Windows_Forms_DataGridViewTextBoxColumn_2) | Out-Null
    $ruleGrid.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 71
    $ruleGrid.Location = $System_Drawing_Point
    $ruleGrid.Name = "ruleGrid"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 269
    $System_Drawing_Size.Width = 444
    $ruleGrid.Size = $System_Drawing_Size
    $ruleGrid.TabIndex = 1
    
    $form1.Controls.Add($ruleGrid)
    
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    $label1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 12, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 9
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 146
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 0
    $label1.Text = "Global Rules"
    $label1.add_Click($handler_label1_Click)
    
    $form1.Controls.Add($label1)

    $ruleGrid.add_CellMouseDoubleClick{
        $ruleGrid.SelectedRows | ForEach-Object {
            GenerateRuleConfig -index $_.Index -isNew $false -isGlobal $true
        }
        . $fillGrid
    }

    . $fillGrid
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog() | Out-Null
    
} #End Function
    
#Call the Function
    