<# Monitored folder View
   --------------------------------
   Author: Severin Nauer           
#>
function GenerateMonitoredFolder {

    param (
        [string] $name,
        [string] $path,
        [boolean] $new,
        [int]$index
    )
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 02.05.2020 09:55
    # Generated By: severin.nauer
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $cancelButton = New-Object System.Windows.Forms.Button
    $deleteButton = New-Object System.Windows.Forms.Button
    $saveButton = New-Object System.Windows.Forms.Button
    $pathpicker = New-Object System.Windows.Forms.Button
    $pathBox = New-Object System.Windows.Forms.TextBox
    $label2 = New-Object System.Windows.Forms.Label
    $nameBox = New-Object System.Windows.Forms.TextBox
    $label1 = New-Object System.Windows.Forms.Label
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $cancelButton_OnClick = 
    {
        $form1.Close()
    }
    

    $deleteButton_OnClick = 
    {
        if (-Not $new) {
            #Deletes the opened Folder in the config json
            DeleteFolder $index
        }
        $form1.Close()
    }
    
    $handler_saveButton_Click = 
    {
        $folder = New-Object psobject -Property @{name = $nameBox.Text; path = $pathBox.Text; types = @() }
        #Adds a folder if $new or replaces existing folder with new values 
        if ($new) {
            AddFolder $folder
        }
        else {
            EditFolder $folder $index
        }
        $form1.Close()
    }
    #Opens the path picker and writes the value into the textbox
    $handler_pathpicker_Click = 
    {
        Import-Module ".\Utils\pathpicker.psm1"
        
        $path = PickPath
        
        if ($path.Length -gt 0) {
            $pathBox.Text = $path[1]
        }
    }
    
    $OnLoadForm_StateCorrection =
    { #Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 134
    $System_Drawing_Size.Width = 440
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Monitored folder"
    
    
    $cancelButton.DataBindings.DefaultDataSourceUpdateMode = 0
    $deleteButton.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 268
    $System_Drawing_Point.Y = 99
    $cancelButton.Location = $System_Drawing_Point
    $cancelButton.Name = "cancelButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $cancelButton.Size = $System_Drawing_Size
    $cancelButton.TabIndex = 6
    $cancelButton.Text = "Cancel"
    $cancelButton.UseVisualStyleBackColor = $True
    $cancelButton.add_Click($cancelButton_OnClick)

    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 20
    $System_Drawing_Point.Y = 99

    $deleteButton.Location = $System_Drawing_Point
    $deleteButton.Name = "deleteButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $deleteButton.Size = $System_Drawing_Size
    $deleteButton.TabIndex = 7
    $deleteButton.Text = "Delete"
    $deleteButton.UseVisualStyleBackColor = $True
    $deleteButton.add_Click($deleteButton_OnClick)
    
    
    $form1.Controls.Add($cancelButton)
    
    
    $saveButton.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 349
    $System_Drawing_Point.Y = 99
    $saveButton.Location = $System_Drawing_Point
    $saveButton.Name = "saveButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $saveButton.Size = $System_Drawing_Size
    $saveButton.TabIndex = 5
    $saveButton.Text = "Save"
    $saveButton.UseVisualStyleBackColor = $True
    $saveButton.add_Click($handler_saveButton_Click)
    
    $form1.Controls.Add($saveButton)
    
    
    $pathpicker.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 398
    $System_Drawing_Point.Y = 53
    $pathpicker.Location = $System_Drawing_Point
    $pathpicker.Name = "pathpicker"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 22
    $System_Drawing_Size.Width = 26
    $pathpicker.Size = $System_Drawing_Size
    $pathpicker.TabIndex = 4
    $pathpicker.Text = "..."
    $pathpicker.UseVisualStyleBackColor = $True
    $pathpicker.add_Click($handler_pathpicker_Click)
    
    $form1.Controls.Add($pathpicker)
    
    $pathBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 70
    $System_Drawing_Point.Y = 54
    $pathBox.Location = $System_Drawing_Point
    $pathBox.Name = "pathBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 328
    $pathBox.Size = $System_Drawing_Size
    $pathBox.TabIndex = 3
    
    $form1.Controls.Add($pathBox)
    
    $label2.DataBindings.DefaultDataSourceUpdateMode = 0
    $label2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 56
    $label2.Location = $System_Drawing_Point
    $System_Windows_Forms_Padding = New-Object System.Windows.Forms.Padding
    $System_Windows_Forms_Padding.Bottom = 0
    $System_Windows_Forms_Padding.Left = 3
    $System_Windows_Forms_Padding.Right = 3
    $System_Windows_Forms_Padding.Top = 2
    $label2.Margin = $System_Windows_Forms_Padding
    $label2.Name = "label2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 51
    $label2.Size = $System_Drawing_Size
    $label2.TabIndex = 2
    $label2.Text = "Path:"
    
    $form1.Controls.Add($label2)
    
    $nameBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 70
    $System_Drawing_Point.Y = 12
    $nameBox.Location = $System_Drawing_Point
    $nameBox.Name = "nameBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 139
    $nameBox.Size = $System_Drawing_Size
    $nameBox.TabIndex = 1
    
    $form1.Controls.Add($nameBox)
    $form1.Controls.Add($deleteButton)
    
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    $label1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 13
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 51
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 0
    $label1.Text = "Name:"
    $label1.add_Click($handler_label1_Click)

    #fills name and path from params to ui
    $nameBox.Text = $name
    $pathBox.Text = $path
    
    $form1.Controls.Add($label1)
    
    #endregion Generated Form Code
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Disable Resize
    $form1.FormBorderStyle = 3
    $form1.MaximizeBox = $false
    #Show the Form
    $form1.ShowDialog() | Out-Null
    
} #End Function


Export-ModuleMember -Function GenerateMonitoredFolder