#Generated Form Function
function GenerateRuleConfig {

    param(
        [int]$folderIndex,
        [int]$index,
        [boolean]$isGlobal,
        [boolean]$isNew
    )
    ########################################################################
    # Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
    # Generated On: 05.05.2020 08:10
    # Generated By: severin.nauer
    ########################################################################
    
    #region Import the Assemblies
    [reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
    [reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
    #endregion
    
    #region Generated Form Objects
    $form1 = New-Object System.Windows.Forms.Form
    $deleteButton = New-Object System.Windows.Forms.Button
    $maxBox = New-Object System.Windows.Forms.NumericUpDown
    $label4 = New-Object System.Windows.Forms.Label
    $minBox = New-Object System.Windows.Forms.NumericUpDown
    $label3 = New-Object System.Windows.Forms.Label
    $pathPicker = New-Object System.Windows.Forms.Button
    $destBox = New-Object System.Windows.Forms.TextBox
    $label2 = New-Object System.Windows.Forms.Label
    $typeBox = New-Object System.Windows.Forms.TextBox
    $label1 = New-Object System.Windows.Forms.Label
    $cancelButton = New-Object System.Windows.Forms.Button
    $saveButton = New-Object System.Windows.Forms.Button
    $InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
    #endregion Generated Form Objects

    $getRuleFromData = {
        return New-Object psobject -Property @{
            type  = $typeBox.Text
            rules = New-Object psobject -Property @{
                minsize     = $minBox.Value
                maxsize     = $maxBox.Value
                destination = $destBox.Text
            }
        }
    }
    
    #----------------------------------------------
    #Generated Event Script Blocks
    #----------------------------------------------
    #Provide Custom Code for events specified in PrimalForms.
    $saveButton_OnClick = 
    {
        Import-Module ".\Utils\config.psm1" -Verbose -Force
        $rule = . $getRuleFromData
        if (-not $isGlobal) {
            if ($isNew) {
                $Script:selectedFolder.types += $rule
                EditFolder $Script:selectedFolder -index $folderIndex -withTypes $true
            }
            else {
                $Script:selectedFolder.types[$index] = $rule
                EditFolder $Script:selectedFolder -index $folderIndex -withTypes $true
            }
        }
        else {
            if ($isNew) {
                AddGlobalRule $rule
            }
            else {
                EditGlobalRule $rule $index
            }
        }
        $form1.Close()
    
    }
    
    $handler_pathPicker_Click = 
    {
        Import-Module ".\Utils\pathpicker.psm1" -Verbose -Force
        $path = PickPath
        
        if ($path.Length -gt 0) {
            $destBox.Text = $path[1]
        }
    }
    
    $handler_deleteButton_Click = 
    {
        Import-Module ".\Utils\config.psm1" -Verbose -Force
        if (-not $isNew) {
            if (-not $isGlobal) {
                $rules = [System.Collections.ArrayList]$Script:selectedFolder.types
                $rules.RemoveAt($index)
                $Script:selectedFolder.types = $rules.ToArray()
                EditFolder $Script:selectedFolder -index $folderIndex -withTypes $true
            }
            else {
                DeleteGlobalRule $index
            }
        }
        $form1.Close()
    
    }
    

    $ruleCancel_onClick = {
        $form1.Close()
    }


    

    

    
    $OnLoadForm_StateCorrection =
    { #Correct the initial state of the form to prevent the .Net maximized form issue
        $form1.WindowState = $InitialFormWindowState
    }
    
    #----------------------------------------------
    #region Generated Form Code
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 241
    $System_Drawing_Size.Width = 400
    $form1.ClientSize = $System_Drawing_Size
    $form1.DataBindings.DefaultDataSourceUpdateMode = 0
    $form1.Name = "form1"
    $form1.Text = "Rule config"
    
    
    $deleteButton.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 13
    $System_Drawing_Point.Y = 206
    $deleteButton.Location = $System_Drawing_Point
    $deleteButton.Name = "deleteButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $deleteButton.Size = $System_Drawing_Size
    $deleteButton.TabIndex = 11
    $deleteButton.Text = "delete"
    $deleteButton.UseVisualStyleBackColor = $True
    $deleteButton.add_Click($handler_deleteButton_Click)
    
    $form1.Controls.Add($deleteButton)
    
    $maxBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 97
    $System_Drawing_Point.Y = 133
    $maxBox.Location = $System_Drawing_Point
    $maxBox.Name = "maxBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 120
    $maxBox.Size = $System_Drawing_Size
    $maxBox.TabIndex = 10
    $maxBox.Maximum = 10000
    
    $form1.Controls.Add($maxBox)
    
    $label4.DataBindings.DefaultDataSourceUpdateMode = 0
    $label4.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 133
    $label4.Location = $System_Drawing_Point
    $label4.Name = "label4"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label4.Size = $System_Drawing_Size
    $label4.TabIndex = 9
    $label4.Text = "Max size:"
    
    $form1.Controls.Add($label4)
    
    $minBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 97
    $System_Drawing_Point.Y = 95
    $minBox.Location = $System_Drawing_Point
    $minBox.Name = "minBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 120
    $minBox.Size = $System_Drawing_Size
    $minBox.TabIndex = 8
    $minBox.Maximum = 9999
    
    $form1.Controls.Add($minBox)
    
    $label3.DataBindings.DefaultDataSourceUpdateMode = 0
    $label3.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 95
    $label3.Location = $System_Drawing_Point
    $label3.Name = "label3"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label3.Size = $System_Drawing_Size
    $label3.TabIndex = 7
    $label3.Text = "Min size:"
    
    $form1.Controls.Add($label3)
    
    
    $pathPicker.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 368
    $System_Drawing_Point.Y = 58
    $pathPicker.Location = $System_Drawing_Point
    $pathPicker.Name = "pathPicker"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 22
    $System_Drawing_Size.Width = 24
    $pathPicker.Size = $System_Drawing_Size
    $pathPicker.TabIndex = 6
    $pathPicker.Text = "..."
    $pathPicker.UseVisualStyleBackColor = $True
    $pathPicker.add_Click($handler_pathPicker_Click)
    
    $form1.Controls.Add($pathPicker)
    
    $destBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 97
    $System_Drawing_Point.Y = 59
    $destBox.Location = $System_Drawing_Point
    $destBox.Name = "destBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 271
    $destBox.Size = $System_Drawing_Size
    $destBox.TabIndex = 5
    
    $form1.Controls.Add($destBox)
    
    $label2.DataBindings.DefaultDataSourceUpdateMode = 0
    $label2.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 61
    $label2.Location = $System_Drawing_Point
    $label2.Name = "label2"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 100
    $label2.Size = $System_Drawing_Size
    $label2.TabIndex = 4
    $label2.Text = "Destination:"
    
    $form1.Controls.Add($label2)
    
    $typeBox.DataBindings.DefaultDataSourceUpdateMode = 0
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 97
    $System_Drawing_Point.Y = 17
    $typeBox.Location = $System_Drawing_Point
    $typeBox.Name = "typeBox"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 20
    $System_Drawing_Size.Width = 87
    $typeBox.Size = $System_Drawing_Size
    $typeBox.TabIndex = 3
    
    $form1.Controls.Add($typeBox)
    
    $label1.DataBindings.DefaultDataSourceUpdateMode = 0
    $label1.Font = New-Object System.Drawing.Font("Microsoft Sans Serif", 9.75, 0, 3, 1)
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 12
    $System_Drawing_Point.Y = 18
    $label1.Location = $System_Drawing_Point
    $label1.Name = "label1"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 21
    $System_Drawing_Size.Width = 50
    $label1.Size = $System_Drawing_Size
    $label1.TabIndex = 2
    $label1.Text = "Type:"
    
    $form1.Controls.Add($label1)
    
    
    $cancelButton.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 222
    $System_Drawing_Point.Y = 206
    $cancelButton.Location = $System_Drawing_Point
    $cancelButton.Name = "cancelButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $cancelButton.Size = $System_Drawing_Size
    $cancelButton.TabIndex = 1
    $cancelButton.Text = "Cancel"
    $cancelButton.UseVisualStyleBackColor = $True
    $cancelButton.add_Click($ruleCancel_onClick)
    
    $form1.Controls.Add($cancelButton)
    
    
    $saveButton.DataBindings.DefaultDataSourceUpdateMode = 0
    
    $System_Drawing_Point = New-Object System.Drawing.Point
    $System_Drawing_Point.X = 313
    $System_Drawing_Point.Y = 206
    $saveButton.Location = $System_Drawing_Point
    $saveButton.Name = "saveButton"
    $System_Drawing_Size = New-Object System.Drawing.Size
    $System_Drawing_Size.Height = 23
    $System_Drawing_Size.Width = 75
    $saveButton.Size = $System_Drawing_Size
    $saveButton.TabIndex = 0
    $saveButton.Text = "Save"
    $saveButton.UseVisualStyleBackColor = $True
    $saveButton.add_Click($saveButton_OnClick)
    
    $form1.Controls.Add($saveButton)
    
    #endregion Generated Form Code

    #region fillData
    Import-Module ".\Utils\config.psm1" -Verbose -Force
    $jsonConfig = (ImportConfig $configPath)
    if (-not $isGlobal) {
        $Script:selectedFolder = $jsonConfig.folders[$folderIndex]
        if (-not $isNew) {
            $Script:selectedRule = $Script:selectedFolder.types[$index]
        }
    }
    else {
        if (-not $isNew) {
            $Script:selectedRule = $jsonConfig.globalTypes[$index]
        }
    }
    if (-not $isNew) {
        $typeBox.Text = $Script:selectedRule.type
        $destBox.Text = $Script:selectedRule.rules.destination
        $minBox.Value = $Script:selectedRule.rules.minsize
        $maxBox.Value = $Script:selectedRule.rules.maxsize
    }
    else {
        $typeBox.Text = ""
        $destBox.Text = ""
        $minBox.Value = 0
        $maxBox.Value = 0
    }

    #endregion
    
    #Save the initial state of the form
    $InitialFormWindowState = $form1.WindowState
    #Init the OnLoad event to correct the initial state of the form
    $form1.add_Load($OnLoadForm_StateCorrection)
    #Show the Form
    $form1.ShowDialog() | Out-Null
    
} #End Function
    
    